### ISSUE TITLE
[Request] Support for Error Detection

### ISSUE THREAD

**Issue by leoherzog** [ipapi-co/ipapi-nodejs#2]
Thanks for this project, it's great! I wish there was a way to catch errors (such as connectivity errors).

```javascript
const ip = require('ipapi.co');

ip.location(ipLocationDetermined);

function ipLocationDetermined(loc) {
  if (!loc || error) {
    // never reaches here if there's a problem
  }
}
```
There is no place that I could wrap a `try...catch` block to catch errors, and the `ip` functions don't throw an `error` object if something goes wrong. The execution just halts.

![](https://i.imgur.com/pEVXZHg.png)

**Comment by ipapi-co** [comment]
@xd1936 Thanks for the PR. We'll review it and add it in the next release.

**Comment by ghost** [comment]
Any updates on this? This is something I really need.

**Comment by ipapi-co** [comment]
The npm package [ipapi.co](https://www.npmjs.com/package/ipapi.co) has been updated with the PR.

**Comment by ghost** [comment]
Could you add some examples for this in the readme?

**Comment by ipapi-co** [comment]
@archiebaer We've got some examples here in the [readme](https://github.com/ipapi-co/ipapi-nodejs/blob/master/README.md). We would be happy to add more. Can you let us know what type of additional examples should be added ?

**Comment by ghost** [comment]
Examples showing error detection.
